# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ca0bf0b74878e7257413f6b2aa4216f1ddfd9f1f9dbc91be76b9374abf584084e7a6a3f099ec3be12040bf57a66389387571a8b70a520b376a5093f5126f6cb5

test:
  secret_key_base: 26bca75dd10d1387be451878d970acc16337399c571cf8a2c9d0586092429b90ad6ed1dc0753bc07b7b859ea931ac24fc7797c42e284b6d24c13e6d7135be086

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
